### ISSUE TITLE
Wrong timeformat in proving-logs

### ISSUE THREAD

**Issue by rjan90** [filecoin-project/rust-fil-logger#17]
Hi! We are getting some reports that when doing windowPoSt the timezones in the logs change from their local-time to UTC, which seems to come from the changes in #14

```
May 07 15:30:52 mXJHY lotus-miner[13876]: 2022-05-07T15:30:52.370+0800        DEBUG        advmgr        sector-storage/sched.go:458        SCHED Acceptable win: [[] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] [] []]
May 07 15:30:52 mXJHY lotus-miner[13876]: 2022-05-07T07:30:52.778 INFO storage_proofs_core::compound_proof > vanilla_proofs:finish
May 07 15:30:52 mXJHY lotus-miner[13876]: 2022-05-07T07:30:52.783 INFO storage_proofs_core::compound_proof > snark_proof:start
```

Also seeing this log when running a wdPoSt-worker.
```
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset  
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
```

Was just wondering if there is a way to get local-time in the logs, instead of UTC? As debugging/searching logs is easier when the time-format is in local time. Feel free to close this if the cause for this time-mismatch is located in some other repo.

**Comment by vmx** [comment]
This issue occurs in multithreaded programs, and Lotus is multithreaded. Lotus would need to initialize the logger while it's still single threaded (I don't know if that's possible in Go). Then you would get the local time.

If you compile from source, you can try setting `RUSTFLAGS="--cfg unsound_local_offset"`, though be aware that it [might lead to unexpected segmentation faults](https://docs.rs/time/0.3.5/time/#feature-flags).

**Comment by rjan90** [comment]
Thanks for the detailed explenation.😄 I will close this and rather add your comment in the Lotus-issue!

**Comment by vmx** [comment]
The folks from `chrono` are working on a proper fix at https://github.com/chronotope/chrono/pull/677. `flexi_logger` has already a way to use `chrono` for that offset calculation, so I'd expect that at some time in the future we'll get local times back without any hacks.
