### ISSUE TITLE
why extra " at the end of the json log?

### ISSUE THREAD

**Issue by hayeah** [filecoin-project/rust-fil-logger#5]
there is an extra " at the end of the json log. 

bug or feature?

https://github.com/filecoin-project/rust-fil-logger/blob/1729d54d073a05463c1d8bda677cd5fca4bae9a6/src/lib.rs#L77

```
{"level":"debug","ts":"2019-11-11T21:06:45.401+01:00","logger":"simple","caller":"examples/simple.rs:37",",sg":"debug information"}"
```

**Comment by vmx** [comment]
Thanks certainly a bug, thanks for the report.
