### ISSUE TITLE
inconsistent timestamp format from ipfs/go-log

### ISSUE THREAD

**Issue by hayeah** [filecoin-project/rust-fil-logger#7]
Go and Rust loggers output timestamps that are slightly different: 

```
lotusLogTimestamp := "2006-01-02T15:04:05.000-0700"
lotusRustLogTimestamp := "2006-01-02T15:04:05.000-07:00"
```

Apparently `0700` and `07:00` are both are allowed by ISO8601TimeEncoder (adopted by ipfs/go-log)

https://github.com/ipfs/go-log/blob/master/core.go#L105

This inconsistency is annoying when parsing the timestamps logs. The easy change is probably just change this to fit go's timezone format.

Or, adopt a non-flexible timestamp format like RFC3339Nano. "2006-01-02T15:04:05.999999999Z07:00"

**Comment by vmx** [comment]
@hayeah sorry, somehow I missed that issue. You are right, the output should be the same as with Go. I'll fix that issue.

**Comment by vmx** [comment]
Thanks again for the report and sorry that it took so long. A released a new version with the fix.
